#ifndef RE_PYTHON_TYPES_IRODS_DATAOBJOPENANDSTAT_HPP
#define RE_PYTHON_TYPES_IRODS_DATAOBJOPENANDSTAT_HPP

namespace irods::re::python::types
{
	void export_OpenStat();
}

#endif // RE_PYTHON_TYPES_IRODS_DATAOBJOPENANDSTAT_HPP
