#ifndef RE_PYTHON_TYPES_IRODS_GUIPROGRESSCALLBACK_HPP
#define RE_PYTHON_TYPES_IRODS_GUIPROGRESSCALLBACK_HPP

namespace irods::re::python::types
{
	void export_OperProgress();
}

#endif // RE_PYTHON_TYPES_IRODS_GUIPROGRESSCALLBACK_HPP
