#ifndef RE_PYTHON_TYPES_IRODS_RODSGENERALUPDATE_HPP
#define RE_PYTHON_TYPES_IRODS_RODSGENERALUPDATE_HPP

namespace irods::re::python::types
{
	void export_GeneralUpdateInp();
}

#endif // RE_PYTHON_TYPES_IRODS_RODSGENERALUPDATE_HPP
