#ifndef RE_PYTHON_TYPES_IRODS_STRUCTFILEEXTANDREG_HPP
#define RE_PYTHON_TYPES_IRODS_STRUCTFILEEXTANDREG_HPP

namespace irods::re::python::types
{
	void export_StructFileExtAndRegInp();
}

#endif // RE_PYTHON_TYPES_IRODS_STRUCTFILEEXTANDREG_HPP
